### ISSUE TITLE
AlgoliaInspect crashes when it tries to return an error

### ISSUE THREAD

**Issue by matt-in-a-hat** [wilr/silverstripe-algolia#8]
```
ERROR [Emergency]: Uncaught BadMethodCallException: Object->__call(): the method 'httpError' does not exist on 'Wilr\SilverStripe\Algolia\Tasks\AlgoliaInspect'
IN GET dev/tasks/AlgoliaInspect
```
e.g. when called without a classname like `./vendor/bin/sake dev/tasks/AlgoliaInspect "ID=1"`

**Comment by wilr** [comment]
Fixed with 27735022554d4179b0a9a9471195295c728d94e2

**Comment by matt-in-a-hat** [comment]
I think the underlying problem is still with `AlgoliaInspect` calling `$this->httpError(` which doesn't exist on that class/hierarchy
